branch-defaults:
  default:
    environment: iapps
    group_suffix: null
environment-defaults:
  itribeapps:
    branch: null
    repository: null
  itribepro:
    branch: null
    repository: null
global:
  application_name: ipro
  branch: null
  default_ec2_keyname: apppro
  default_platform: Docker 17.09.1-ce
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
